# Generated by Django 5.1.3 on 2024-11-11 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationPrepay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('commune', models.CharField(max_length=255)),
                ('quartier', models.CharField(max_length=255)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('postnom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('identifiant_client', models.CharField(max_length=50, unique=True)),
                ('categorie', models.CharField(choices=[('menage', 'Ménage'), ('bar', 'Bar'), ('entreprise', 'Entreprise'), ('eglise', 'Église'), ('autres', 'Autres')], max_length=20)),
                ('montant_a_payer', models.IntegerField(choices=[(10000, '10 000 FCFA'), (20000, '20 000 FCFA'), (50000, '50 000 FCFA')])),
                ('statut_paiement', models.BooleanField(default=False)),
                ('paiement_verifie', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.stationprepay')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_transaction', models.CharField(help_text='ID de transaction unique', max_length=255)),
                ('numero_operant', models.CharField(help_text="Numéro de l'opérant traitant la transaction", max_length=100)),
                ('date_confirmation', models.DateTimeField(auto_now_add=True)),
                ('statut_confirmation', models.BooleanField(default=False)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation', to='core.payment')),
            ],
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='communications/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='core.stationprepay')),
            ],
        ),
    ]
