# Generated by Django 5.1.3 on 2024-11-12 11:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_paymentnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='id_transaction',
            field=models.CharField(default=uuid.uuid4, help_text='ID de transaction unique', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='numero_operant',
            field=models.CharField(default='', help_text="Numéro de l'opérant traitant la transaction", max_length=100),
        ),
    ]
