# Generated by Django 5.1.3 on 2024-11-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_payment_id_transaction_payment_numero_operant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='id_transaction',
            field=models.CharField(blank=True, help_text='ID de transaction unique', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='numero_operant',
            field=models.CharField(blank=True, help_text="Numéro de l'opérant traitant la transaction", max_length=100, null=True),
        ),
    ]
