# Generated by Django 5.1.3 on 2024-11-13 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_cart_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment2',
            name='station_prepay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.stationprepay'),
        ),
    ]
